apiVersion: v2
name: mail-service
description: Mail Service - Email Delivery via Resend API
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: common
    version: "0.1.1"
    repository: "file://../../../shared/helm-library"
