services:
  client-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ClientService
    ports:
      - "8082:8082"
    environment:
      - SQL_USERNAME=sa
      - SQL_PASSWORD=ClientService@2024!
      - SQL_ADDRESS=mssql:1433
      - SQL_DATABASE_NAME=master
      - CLIENT_SERVICE_PORT=:8082
      - KAFKA_BROKER=AuthServiceKafka:29092
      - KAFKA_TOPIC=UserCreated
      - KAFKA_GROUP_ID=client-service-consumer
      - ACCOUNT_SERVICE_URL=http://account-service:8083
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - triobank-network
    restart: unless-stopped

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ClientServiceMSSQL
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ClientService@2024!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - triobank-network
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'ClientService@2024!' -Q 'SELECT 1' -C -N || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped

networks:
  triobank-network:
    external: true
    name: triobank-network

volumes:
  mssql_data:
