
replicaCount: 1

image:
  tag: "dev"
  pullPolicy: Always

app:
  environment: development
  logLevel: debug
  logFormat: text

resources:
  requests:
    memory: 256Mi
    cpu: 50m
  limits:
    memory: 1024Mi
    cpu: 500m

databases:
  mssql:
    externalName: host.minikube.internal  # Minikube Linux gateway to host
    portName: mssql

database:
  name: ledger_db

