
apiVersion: v2
name: kafka-ui
description: Kafka UI - Kafka cluster izleme ve yönetim arayüzü
type: application
version: 0.1.0
appVersion: "0.7.2"

dependencies:
  - name: kafka-ui
    version: "0.7.2"
    repository: https://provectus.github.io/kafka-ui-charts
