
apiVersion: v2
name: kafka-operator
description: Strimzi Kafka Operator - Kafka cluster y√∂netimi
type: application
version: 0.1.0
appVersion: "0.49.0"

dependencies:
  - name: strimzi-kafka-operator
    version: "0.49.0"
    repository: https://strimzi.io/charts/
