
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/akyurekridvan2101/TrioBank.git
    targetRevision: feat/platform-hybrid-architecture
    path: infrastructure/kubernetes/argocd/apps
    
    helm:
      values: |
        env: dev
        branch: feat/platform-hybrid-architecture

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true      # Silinen kaynakları temizle
      selfHeal: true   # Değişiklikleri geri al
    syncOptions:
      - CreateNamespace=true
