version: '3.9'
services:
  mongo:
    image: mongo:7.0
    container_name: AuthServiceDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_auth_data:/data/db

  redis:
    image: redis:7.0
    container_name: AuthServiceRedis
    ports:
      - "6379:6379"

volumes:
  mongodb_auth_data:
